### ISSUE TITLE
SELinux support

### ISSUE THREAD

**Issue by oszi** [oszi/dockerfiles#2]
Waiting for upstream overlayfs support.

**Comment by nightling** [comment]
Workarounds for now: aa127cfe407ba6805e4ccb55d79d7381cbb6c04b

**Comment by nightling** [comment]
Related commits: e3635d4443649a131ffe01bef894bd2735421252, 918e56b3c11e4ea8a154f00a6550cea80e94e137, 0f57602d919d52da80eb904f86d41095e29872e4

Desktop containers and overlayfs are still problematic.

**Comment by oszi** [comment]
Solved in kernel 4.8+ with overlay2.
